Repository mikepenz/AboutLibraries, pull requests merged in 2020-10, with the labels that each got.

#533 [CI] Automate release via GitHub actions | FIX #532
  .github/ci-gradle.properties
  .github/workflows/ci.yml
  .github/workflows/gradle-wrapper-validation.yml
  DEV/default-detekt-config.yml
  Dangerfile
  Gemfile
  Gemfile.lock
  app/build.gradle
  build.gradle
  configurations.gradle
  detekt.gradle
  gradle-release.gradle
  plugin/build.gradle
  plugin/src/main/groovy/com/mikepenz/aboutlibraries/plugin/AboutLibrariesProcessor.groovy
  plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/DependencyCollector.kt
Labels: enhancement

#534 [CI] Improve releasing plugin
  .github/workflows/ci.yml
  Dangerfile
  README.md
  app/build.gradle
  build.gradle
  gradle-release.gradle
  gradle.properties
  plugin/build.gradle
  plugin/src/main/groovy/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExportTask.groovy
  plugin/src/main/groovy/com/mikepenz/aboutlibraries/plugin/AboutLibrariesPlugin.groovy
Labels: enhancement

#539 Code cleanup
  Gemfile.lock
  README.md
  app/src/main/java/com/mikepenz/aboutlibraries/sample/FragmentActivity.kt
  app/src/main/res/menu/fragment.xml
  library-core/src/main/java/com/mikepenz/aboutlibraries/Libs.kt
  library-definitions/src/main/res/values/library_android_upload_service_strings.xml
  library-definitions/src/main/res/values/library_switchdatetimepicker_strings.xml
  library/src/main/java/com/mikepenz/aboutlibraries/LibsBuilder.kt
  library/src/main/java/com/mikepenz/aboutlibraries/LibsConfiguration.kt
  library/src/main/java/com/mikepenz/aboutlibraries/util/UIUtils.kt
  plugin/src/main/groovy/com/mikepenz/aboutlibraries/plugin/AboutLibrariesTask.groovy
Labels: hacktoberfest-accepted

#542 Automatic changelog generation for releases
  .github/config/configuration.json
  .github/workflows/ci.yml
  README.md
  app/build.gradle
Labels: other

#545 Fallback to licenseId if no licenseIds are specified
  library-core/src/main/java/com/mikepenz/aboutlibraries/Libs.kt
Labels: fix

#546 Update dependencies
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: feature
