Repository mikepenz/AboutLibraries, pull requests merged in 2022-08, with the labels that each got.

#785 Dependency updates | Compose 1.2.0 | Compile&TargetSDK 32
  app-desktop/src/main/resources/aboutlibraries.json
  gradle/libs.versions.toml
Labels: feature

#786 Introduce support for `platform` dependencies to be included in report
  README.md
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesCollectorTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExtension.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/DependencyCollector.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/Extensions.kt
Labels: feature

#788 Update plugin implementation notes
  README.md
Labels: other

#790 Use `colorControlNormal` for `SearchView`'s `EditText` color
  aboutlibraries/src/main/java/com/mikepenz/aboutlibraries/ui/LibsActivity.kt
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: fix

#791 Introduce CI workflow for Dependency Submission
  .github/workflows/gradle-dependency-submission.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: other

#792 Adjust buildConfiguration for Dependency submission of `app-desktop` module
  .github/workflows/gradle-dependency-submission.yml
Labels: other

#793 Update `dependency-submisssion` CI pipeline
  .github/workflows/gradle-dependency-submission.yml
Labels: other
