Repository mikepenz/AboutLibraries, pull requests merged in 2022-11, with the labels that each got.

#815 Fix default color for HtmlText and dark theme
  aboutlibraries-compose/src/androidMain/kotlin/com/mikepenz/aboutlibraries/ui/compose/Libraries.kt
Labels: fix

#818 Add support to `prettyPrint` the JSON file
  README.md
  app-desktop/build.gradle.kts
  app-desktop/src/main/resources/aboutlibraries.json
  app/build.gradle
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExtension.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/model/ResultContainer.kt
Labels: feature

#819 Update to compose 1.3.1
  app-desktop/src/main/resources/aboutlibraries.json
  gradle/libs.versions.toml
Labels: feature

#820 Fix plugin mistakenly filtering build variants containing `test` in the name
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/DependencyCollector.kt
Labels: fix

#823 Update GitHub Actions dependencies
  .github/workflows/ci.yml
  .github/workflows/gradle-dependency-submission.yml
Labels: other
