Repository mikepenz/AboutLibraries, pull requests merged in 2023-05, with the labels that each got.

#874 Detect enabled configuration cache for Gradle 8.x
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesPlugin.kt
Labels: fix

#876 Dependency Upgrades | Compose 1.4.3 / Compose-Jb 1.4.0 / Kotlin 1.8.21
  aboutlibraries-compose/build.gradle.kts
  aboutlibraries-compose/src/androidMain/AndroidManifest.xml
  aboutlibraries-core/build.gradle.kts
  aboutlibraries-core/src/androidMain/AndroidManifest.xml
  aboutlibraries/build.gradle
  aboutlibraries/src/main/AndroidManifest.xml
  app-desktop/build.gradle.kts
  app/build.gradle
  app/src/main/AndroidManifest.xml
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  plugin-build/gradle/wrapper/gradle-wrapper.properties
Labels: feature

#877 Adjustments on `SpdxLicense` class
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/mapping/SpdxLicense.kt
Labels: fix

#880 Failsafe on missing `title` for library
  aboutlibraries-core/src/androidMain/kotlin/com/mikepenz/aboutlibraries/util/AndroidParser.kt
  aboutlibraries-core/src/multiplatformMain/kotlin/com/mikepenz/aboutlibraries/util/MultiplatformParser.kt
  aboutlibraries/src/main/java/com/mikepenz/aboutlibraries/ui/LibsSupportFragment.kt
Labels: feature

#883 Drop bundled `SpdxLicense` from `core` module
  aboutlibraries-core/src/commonMain/kotlin/com/mikepenz/aboutlibraries/entity/SpdxLicense.kt
Labels: other

#882 Upgrade dependencies | Gradle Build 8.0.1 | KotlinX Serailization 1.5.1
  .github/workflows/ci.yml
  .github/workflows/gradle-dependency-submission.yml
  aboutlibraries/src/main/java/com/mikepenz/aboutlibraries/ui/LibsActivity.kt
  aboutlibraries/src/main/java/com/mikepenz/aboutlibraries/util/UIUtils.kt
  app/src/main/java/com/mikepenz/aboutlibraries/sample/FragmentActivity.kt
  gradle/libs.versions.toml
Labels: dependencies
