Repository mikepenz/AboutLibraries, pull requests merged in 2024-11, with the labels that each got.

#1031 Update README links
  README.md
Labels: other

#1032 Major dependency upgrades | Compose-jb 1.7.0 / Compose 1.7.0 | Kotlin 2.0.21
  aboutlibraries-compose-m2/build.gradle.kts
  aboutlibraries-compose-m3/build.gradle.kts
  aboutlibraries-core/build.gradle.kts
  aboutlibraries/build.gradle
  app-desktop/src/main/resources/aboutlibraries.json
  app-test/files/aboutlibraries.json
  app-wasm/src/commonMain/composeResources/files/aboutlibraries.json
  app/build.gradle
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: feature

#1035 Update Compose to 1.7.1 | Serialization 1.7.3
  gradle/libs.versions.toml
Labels: dependencies

#1036 Refactor gradle property retrieval with lazy APIs | Upgrade Gradle to 8.11 | Increase gradle min requirement to 7.x
  app-desktop/README.md
  app-desktop/src/main/resources/aboutlibraries.json
  app-test/files/aboutlibraries.json
  app-wasm/README.md
  app-wasm/build.gradle.kts
  app-wasm/src/commonMain/composeResources/files/aboutlibraries.json
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  plugin-build/build.gradle
  plugin-build/plugin/build.gradle
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExportComplianceTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExportTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesPlugin.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesPluginAndroidExtension.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/BaseAboutLibrariesTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/model/DefaultModuleComponentIdentifier.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/model/DefaultModuleIdentifier.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/model/DefaultModuleVersionIdentifier.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/Extensions.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/LibrariesProcessor.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/PomLoader.kt
Labels: feature

#1038 Update CI to run Lint on Gradle Plugin
  .github/workflows/ci.yml
  .github/workflows/gradle-dependency-submission.yml
  .github/workflows/static.yml
Labels: other

#1040 Fix dependency collection to match gradle task
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/DependencyCollector.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/Extensions.kt
Labels: fix
