Repository mikepenz/AboutLibraries, pull requests merged in 2025-04, with the labels that each got.

#1107 Provide configuration option for `outputPath`
  README.md
  app-desktop/README.md
  app-desktop/build.gradle.kts
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExtension.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesPlugin.kt
Labels: feature

#1108 Update to 1.8.1 of KotlinX serialization
  gradle/libs.versions.toml
Labels: dependencies

#1109 Make dialog license text focusable
  aboutlibraries-compose-m2/src/commonMain/kotlin/com/mikepenz/aboutlibraries/ui/compose/SharedLibraries.kt
  aboutlibraries-compose-m3/src/commonMain/kotlin/com/mikepenz/aboutlibraries/ui/compose/m3/SharedLibraries.kt
Labels: feature

#1111 Refactor Gradle Plugin | Use Properties for configuration
  MIGRATION.md
  README.md
  app-desktop/build.gradle.kts
  app-desktop/src/commonMain/composeResources/files/aboutlibraries.json
  app-test/build.gradle.kts
  app-test/files/aboutlibraries.json
  app-wasm/README.md
  app-wasm/build.gradle.kts
  app-wasm/src/commonMain/composeResources/files/aboutlibraries.json
  app/README.md
  app/build.gradle.kts
  gradle.properties
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesCollectorTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExportComplianceTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExportTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExtension.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesFundingTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesIdTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesPlugin.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesPluginAndroidExtension.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/BaseAboutLibrariesTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/model/CollectedContainer.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/model/ResultContainer.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/DependencyCollector.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/LibrariesProcessor.kt
Labels: feature

#1112 Disable config cache in CI for publishing
  .github/workflows/ci.yml
  gradle.properties
  settings.gradle.kts
Labels: other

#1114 Add improved default license dialog
  aboutlibraries-compose-m2/api/android/aboutlibraries-compose-m2.api
  aboutlibraries-compose-m2/api/jvm/aboutlibraries-compose-m2.api
  aboutlibraries-compose-m2/src/androidMain/kotlin/com/mikepenz/aboutlibraries/ui/compose/AndroidLibraries.kt
  aboutlibraries-compose-m2/src/commonMain/kotlin/com/mikepenz/aboutlibraries/ui/compose/Libraries.kt
  aboutlibraries-compose-m2/src/commonMain/kotlin/com/mikepenz/aboutlibraries/ui/compose/SharedLibraries.kt
  aboutlibraries-compose-m3/api/android/aboutlibraries-compose-m3.api
  aboutlibraries-compose-m3/api/jvm/aboutlibraries-compose-m3.api
  aboutlibraries-compose-m3/src/androidMain/kotlin/com/mikepenz/aboutlibraries/ui/compose/m3/AndroidLibraries.kt
  aboutlibraries-compose-m3/src/commonMain/kotlin/com/mikepenz/aboutlibraries/ui/compose/m3/Libraries.kt
  aboutlibraries-compose-m3/src/commonMain/kotlin/com/mikepenz/aboutlibraries/ui/compose/m3/SharedLibraries.kt
  aboutlibraries-compose/api/aboutlibraries-compose.klib.api
  aboutlibraries-compose/api/android/aboutlibraries-compose.api
  aboutlibraries-compose/api/jvm/aboutlibraries-compose.api
  aboutlibraries-compose/src/commonMain/kotlin/com/mikepenz/aboutlibraries/ui/compose/util/Extensions.kt
Labels: feature

#1120 [A] Filter out project modules
  plugin-build/plugin/gradle.properties
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/DependencyCollector.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/PomLoader.kt
Labels: fix

#1121 Publish using cross compilation
  .github/workflows/ci.yml
  gradle.properties
  settings.gradle.kts
Labels: other

#1122 CI cleanup
  .github/workflows/ci.yml
Labels: other

#1124 Improve log in case of wrong `exportVariant` being used
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/DependencyCollector.kt
Labels: other

#1137 Add `afterEvaluate` for Android task
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesPlugin.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesPluginAndroidExtension.kt
Labels: fix

#1138 Introduce Gradle Property to pass `outputPath` via CLI
  README.md
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExportComplianceTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExtension.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/BaseAboutLibrariesTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/DependencyCollector.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/Extensions.kt
Labels: feature

#1141 Change `gradleApi` of plugin to `compileOnly`
  plugin-build/plugin/build.gradle.kts
Labels: other

#1143 Compose 1.8.0 / Compose Multiplatform 1.8.0-rc01
  app-desktop/src/commonMain/composeResources/files/aboutlibraries.json
  app-wasm/src/commonMain/composeResources/files/aboutlibraries.json
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: feature

#1146 Refactor plugin to support `org.gradle.configureondemand=true`
  README.md
  app-desktop/src/commonMain/composeResources/files/aboutlibraries.json
  app-test/files/aboutlibraries.json
  app-wasm/src/commonMain/composeResources/files/aboutlibraries.json
  gradle.properties
  gradle/libs.versions.toml
  plugin-build/plugin/build.gradle.kts
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExportComplianceTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExportTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExtension.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesFundingTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesIdTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesPlugin.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/BaseAboutLibrariesTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/mapping/Developer.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/mapping/Funding.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/mapping/License.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/mapping/Organization.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/mapping/Scm.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/mapping/SpdxLicense.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/model/CollectedContainer.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/model/DefaultModuleComponentIdentifier.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/model/DefaultModuleIdentifier.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/model/DefaultModuleVersionIdentifier.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/model/ResultContainer.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/DependencyCollector.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/Extensions.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/LibrariesProcessor.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/LibraryPostProcessor.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/LibraryUtil.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/PomLoader.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/parser/LibraryReader.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/util/parser/PomReader.kt
Labels: feature

#1147 Set the exportVariant for the sample project
  app-desktop/build.gradle.kts
  app-desktop/src/commonMain/composeResources/files/aboutlibraries.json
  app-wasm/README.md
  app-wasm/build.gradle.kts
  app-wasm/src/commonMain/composeResources/files/aboutlibraries.json
  app/build.gradle.kts
Labels: other

#1149 Fix documentation for `outputPath`
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExtension.kt
Labels: other

#1150 Provide variant based tasks for KMP
  README.md
  app-desktop/build.gradle.kts
  app-wasm/README.md
  app-wasm/build.gradle.kts
  plugin-build/plugin/build.gradle.kts
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExportTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesExtension.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesIdTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesPlugin.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesPluginAndroidExtension.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/AboutLibrariesTask.kt
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/BaseAboutLibrariesTask.kt
Labels: feature

#1152 Improve README
  README.md
Labels: other

#1155 Fix exclude fields not set fully
  plugin-build/plugin/src/main/kotlin/com/mikepenz/aboutlibraries/plugin/BaseAboutLibrariesTask.kt
Labels: fix
